--BEFORE TRIGGER
ALTER TABLE T_TRANSACTION ADD F_ASKING_PRICE NUMBER(7,2) NULL; 
 
CREATE OR REPLACE TRIGGER TR_NEW_PRICE 
    BEFORE INSERT OR UPDATE OF F_ASKING_PRICE
        ON T_TRANSACTION 
        FOR EACH ROW 
    BEGIN  
        :NEW.F_ASKING_PRICE := :NEW.F_ASKING_PRICE * 2; 
    END; 
 /
UPDATE T_TRANSACTION SET F_ASKING_PRICE = 500 WHERE F_TRANSACTION_ID = 1; 